### PR TITLE
Added python 3.7 to appveyor.yml

### PR DESCRIPTION
**Pull request by nonZero**

### CODE REVIEW

**Comment by tacaswell** [comment]
You will probably need to update the multi-build sub-module to look at the current devel branch

**Comment by nonZero** [comment]
Hmm... the windows wheels / appveyor is ok.
@jsancho-gpl can you bump multi-build to s newer version?

**Comment by tomkooij** [comment]
@nonzero. Please look into the Travis (Linux/Mac) part. Should be to difficult to fix See tacaswells suggestion. Once everything builds, I'll merge and upload everything to PyPI.

**Comment by nonZero** [comment]
@tacaswell Do you have any idea which commit should we use? devel seems quite broken as well:
https://travis-ci.com/nonZero/pytables-wheels/jobs/164960278

**Comment by tacaswell** [comment]
No, sorry.  "move to current devel" is what I do when the h5py and Matplotlib wheels are broken.  Check what h5py is using on the 2.9 branch (those ran for me over the weekend).

**Comment by nonZero** [comment]
https://github.com/matthew-brett/multibuild/issues/217

**Comment by nonZero** [comment]
@tomkooij fixed :-)

**Comment by tomkooij** [comment]
Nice work @nonZero 

I'm not sure Travis is showing the correct build (probably because of the force-pushes), but I'm going to merge this and uploaded the working wheels to PyPI. 

I'll create an issue for any possible left-overs.

THANKS!

**Pull request merged**
