### PR TITLE
Build windows wheel using appveyor

### PR DESCRIPTION
**Pull request by tomkooij**
I tried using multibuild on windows. First using the bash scripts in cygwin and subsequently by creating `before_install` and `install_run` like scripts in powershell.  Unfortunately, that just didn't work out. Cygwin bites MSVC and powershell does not like conda (activate does not work in powershell). After a lot of fiddling around, I was forced to give up.

Finally, I just copied and clean-up my https://github.com/tomkooij/pytables-wheel-builder which just builds and test everything in a single appveyor script. This is not as portable to other repo's, but works without all the cygwin/powershell troubles.

This builds a wheel in a conda enviroment. Then creates a new env and installs the wheel and runs tests.
Uploading is added yet.

The scripts in /ci/appveyor could maybe be moved to multibuild.

AppVeyor results can be previewed here: https://ci.appveyor.com/project/tomkooij/pytables-wheels

### CODE REVIEW

**Comment by tomkooij** [comment]
@matthew-brett : What do you think of the solution in this PR? It does not use multibuild at all. It certainly is not as flexible. It does however builds windows wheels without much problems. The appveyor build passed: https://ci.appveyor.com/project/tomkooij/pytables-wheels

This  can also be extended to for example astropy: https://github.com/tomkooij/astropy-wheels

**Comment by matthew-brett** [comment]
Sorry to be so slow to reply - I've been travelling.  Should have a more reliable connection soon.  Will have a look soon and get back to you.

**Comment by matthew-brett** [comment]
Sure, looks good.   Maybe worth moving some of this machinery into multibuild?

**Comment by tomkooij** [comment]
I'll create a PR for multibuild.

I'm not sure why travis fails, it should be unrelated to this PR.

**Comment by tomkooij** [comment]
Appveyor passes: https://ci.appveyor.com/project/tomkooij/pytables-wheels/build/1.0.101

@matthew-brett: Please enable appveyor for this repo.

**Comment by matthew-brett** [comment]
Done.​

**Pull request merged**
